### PR TITLE
chore(install-tools): make tooling compatible on darwin/arm64

### PR DESCRIPTION
**Pull request by anleg**
### What does this PR do?

Rewrite tool installation bash scripts to be able to test and contribute to the project with Darwin Arm64 (Silicon)

### Motivation

Be able to develop new feature on a Mac M1

### Additional Notes

Some tools are not up-to-date and could be upgraded to have the Darwin/Arm64 binary, but I wanted to avoid updating everything and potentially adding breaking changes. So, I've preferred to build/compile the tools.

### Describe your test plan

```bash
rm -rf bin/*
make install-tools
```

### CODE REVIEW

**Review by CharlyF — APPROVED** [review]
I was able to build the controller from my non M1 laptop, just want to get a review from someone else who has a M1.

**Review by khewonc — APPROVED** [review]
I can build the controller from my M1 laptop 👍

**Comment by CharlyF** [comment]
@anleg could you look into the failed job?

```./hack/patch-crds.sh
./hack/install-wwhrd.sh 0.2.4
wwwhrd is not compatible for linux/amd64
Error: make: *** [Makefile:[20](https://github.com/DataDog/watermarkpodautoscaler/runs/6229433543?check_suite_focus=true#step:7:20)7: bin/wwhrd] Error 1
Error: Process completed with exit code 2.```

**Comment by anleg** [comment]
@CharlyF It's fixed :)

**Pull request merged**
